packages:
  - 'packages/*'
allowBuilds:
  '@mongodb-js/zstd': true
  esbuild: true
  node-liblzma: true
minimumReleaseAgeExclude:
  - '@archildata/api-types@0.0.4'
  - ai@7.0.5
  - eve@0.17.1
  - eve@0.20.0

catalog:
  typescript: ^6.0.3
  tsdown: ^0.22.3
  vitest: ^4.1.9
