name: Node Test

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/node-test.yaml'
      - '.github/workflows/node-release.yaml'
  pull_request:
    paths:
      - 'packages/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/node-test.yaml'
      - '.github/workflows/node-release.yaml'

jobs:
  test:
    name: Node Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test
