name: Python Integration

on:
  push:
    branches:
      - main
    paths:
      - 'python/**'
      - '.github/workflows/python-integration.yaml'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python-integration.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  staging:
    name: Staging
    runs-on: ubuntu-latest
    env:
      ARCHIL_API_KEY: ${{ secrets.ARCHIL_API_KEY }}
      ARCHIL_REGION: ${{ secrets.ARCHIL_REGION }}
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: '3.12'
          working-directory: python

      - name: Install package
        working-directory: python
        run: |
          uv venv
          uv pip install -e .

      - name: Run staging integration test
        working-directory: python
        run: uv run --no-sync python integration/sdk_integration_test.py
